apiVersion: v1                                                                            
kind: Service                         
metadata:     
  name: techtrends-nodeport
  namespace: prod                              
spec:                                      
  ports:                     
  - port: 7111               
    protocol: TCP            
    targetPort: 3111
    nodePort: 30014
  selector:
    app: techtrends
  type: NodePort
status:                
  loadBalancer: {}
