apiVersion: v1                                                                            
kind: Service                         
metadata:     
  name: techtrends-nodeport
  namespace: staging                              
spec:                                      
  ports:                     
  - port: 5111
    protocol: TCP            
    targetPort: 3111
    nodePort: 30013
  selector:
    app: techtrends
  type: NodePort
status:                
  loadBalancer: {}
