apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }} 
  name: techtrends
spec:
  replicas: {{ .Values.replicaCount }} 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
        labels:
          app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: techtrends
        livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }} 
              port: {{ .Values.ports.containerPort }} 
        readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }} 
              port: {{ .Values.ports.containerPort }} 
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }} 
            cpu: {{ .Values.resources.requests.cpu }} 
          limits:
            memory: {{ .Values.resources.limits.memory }} 
            cpu: {{ .Values.resources.limits.cpu }} 
        ports:
        - containerPort: {{ .Values.ports.containerPort }} 
          protocol: {{ .Values.ports.protocol }} 
