apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.ports.servicePort }} 
    protocol: {{ .Values.ports.protocol }} 
    targetPort: {{ .Values.ports.containerPort }} 
  type: {{ .Values.serviceType }} 
