namespace:
  name: sandbox
 
image:
  repository: amour3000/techtrends 
  tag: latest
  imagePullPolicy: IfNotPresent

replicaCount: 1

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ports:
  servicePort: 4111
  containerPort: 3111
  protocol: TCP

serviceType: ClusterIP
