name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"
jobs:
  build:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            amour3000/techtrends
          tags: |
            type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./project/
          file: ./project/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - 
        name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v0.13.1
        with:
          valueFile: 'project/helm/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.meta.outputs.tags }}
          branch: main
          commitChange: true
          message: 'Update Image Version to ${{ steps.meta.outputs.tags }}'
